version: "3.7"

services:
  redis:
    image: "bitnami/redis:5.0.4"
    env_file:
      - conf/redis.env
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  postgres:
    image: "postgres"
    env_file:
      - conf/postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  rpc_worker:
    build: rpc
    stdin_open: true
    tty: true
    depends_on:
      - redis
    env_file:
      - conf/fastapi.env
    command: "python worker.py"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
      - rpc_worker
    volumes:
      - "./:/app"
    env_file:
      - conf/fastapi.env
    command: "python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

  datadog:
    build: datadog
    links:
     - redis # ensures that redis is a host that the container can find
     - postgres
     - fastapi # ensures that the web app can send metrics
    env_file:
      - conf/datadog.env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  database-data:
    driver: local
